### ISSUE TITLE
Can this flatten for just document-links?

### ISSUE THREAD

**Issue by stevieflow** [markbrough/flatiati#6]
Hi Mark

Quick question - could this be used to deliver spreadsheets that are a set of document-link from activities, with the relevant data (both at document-link but also the relevant parts of the parent iati-activity)?

**Comment by markbrough** [comment]
This repository is actually really old now! I think maybe you are thinking of this? (to which the answer is probably "sure! but it would need a bit of work")
https://github.com/iati-data-access/iati-flattener
